[package]
name = "standard_map_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.17"
imageproc = "0.22"
image = "0.23"
chrono = "0.4"
rand = "0.8.5"